# Generated by Django 4.0.4 on 2022-04-24 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Who has access'),
        ),
        migrations.AlterField(
            model_name='file',
            name='modifier',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified by'),
        ),
    ]
