# Generated by Django 4.0.4 on 2022-04-24 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_file_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='access',
        ),
        migrations.AddField(
            model_name='file',
            name='access',
            field=models.ManyToManyField(blank=True, related_name='access', to=settings.AUTH_USER_MODEL, verbose_name='Who has access'),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
