# Generated by Django 4.0.4 on 2022-04-26 08:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_file_access_file_access_alter_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=core.models.document_dir_path),
        ),
    ]
