# Generated by Django 4.0.4 on 2022-05-01 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_file_access_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='modifier',
        ),
        migrations.AddField(
            model_name='access',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Timestamp'),
            preserve_default=False,
        ),
    ]
