# Generated by Django 4.0.4 on 2022-05-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_file_modifier_access_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='modified',
        ),
        migrations.AlterField(
            model_name='access',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Timestamp'),
        ),
    ]
